# Generated by Django 5.0.2 on 2024-02-21 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "attr",
                    models.CharField(max_length=200, verbose_name="Qisqa nomi [attr]"),
                ),
                (
                    "attr_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "attr_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "attr_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lavozim",
                "verbose_name_plural": "Lavozimlar",
                "db_table": "employee_positions",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Rasm"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rasm",
                "verbose_name_plural": "Rasmlar",
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "attr",
                    models.CharField(max_length=200, verbose_name="Qisqa nomi [attr]"),
                ),
                (
                    "attr_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "attr_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "attr_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Qisqa nomi [attr]"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat turi",
                "verbose_name_plural": "Xizmat turlari",
                "db_table": "service_type",
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                ("content", models.TextField(null=True, verbose_name="Ma'lumot")),
                ("content_uz", models.TextField(null=True, verbose_name="Ma'lumot")),
                ("content_en", models.TextField(null=True, verbose_name="Ma'lumot")),
                ("content_ru", models.TextField(null=True, verbose_name="Ma'lumot")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Rasm"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tahrirlangan vaqt"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utils.state",
                        verbose_name="Xolati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tizim haqida",
                "verbose_name_plural": "Tizim haqida",
                "db_table": "about",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        max_length=200, verbose_name="Ism va familiyangiz [fullname]"
                    ),
                ),
                (
                    "fullname_uz",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Ism va familiyangiz [fullname]",
                    ),
                ),
                (
                    "fullname_en",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Ism va familiyangiz [fullname]",
                    ),
                ),
                (
                    "fullname_ru",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Ism va familiyangiz [fullname]",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="Manzilingiz"),
                ),
                (
                    "address_uz",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Manzilingiz"
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Manzilingiz"
                    ),
                ),
                (
                    "address_ru",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Manzilingiz"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Rasm"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Telefon raqamingiz"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email manzilingiz"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.employeepositions",
                        verbose_name="Lavozimingiz",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utils.state",
                        verbose_name="Xolati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim",
                "verbose_name_plural": "Xodimlar",
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=200, verbose_name="Telefon raqamlar"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Manzil")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Logo"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, null=True, verbose_name="Facebook manzili"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram manzili"
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Telegram manzili"
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True, null=True, verbose_name="Youtube manzili"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tahrirlangan vaqti"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utils.state",
                        verbose_name="Holati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer[saytni pasti qismi]",
                "verbose_name_plural": "Footer[saytni pastki qismi]",
                "db_table": "footer",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="To'liq nomi [title]"
                    ),
                ),
                ("content", models.TextField(verbose_name="Xizmat haqida ma'lumot")),
                (
                    "content_uz",
                    models.TextField(null=True, verbose_name="Xizmat haqida ma'lumot"),
                ),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Xizmat haqida ma'lumot"),
                ),
                (
                    "content_ru",
                    models.TextField(null=True, verbose_name="Xizmat haqida ma'lumot"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="icons/", verbose_name="Ikonka"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utils.state",
                        verbose_name="Xolati",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.servicetype",
                        verbose_name="Xizmat turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Sarlavha [title]"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Sarlavha [title]"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Sarlavha [title]"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Sarlavha [title]"
                    ),
                ),
                (
                    "content",
                    models.TextField(null=True, verbose_name="Ma'lumot [content]"),
                ),
                (
                    "content_uz",
                    models.TextField(null=True, verbose_name="Ma'lumot [content]"),
                ),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Ma'lumot [content]"),
                ),
                (
                    "content_ru",
                    models.TextField(null=True, verbose_name="Ma'lumot [content]"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tahrirlangan vaqti"
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Chop etilgan vaqt"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
                ),
                ("image", models.ManyToManyField(to="app.image", verbose_name="Rasm")),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utils.state",
                        verbose_name="Xolati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "db_table": "news",
                "indexes": [
                    models.Index(
                        fields=["title", "state", "created_at"],
                        name="news_title_3c8f34_idx",
                    )
                ],
            },
        ),
    ]
