# Generated by Django 5.0.2 on 2024-02-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.employeeposition",
                verbose_name="Lavozimi",
            ),
        ),
        migrations.AlterField(
            model_name="employeeposition",
            name="positions",
            field=models.CharField(max_length=240, verbose_name="Lavozimi"),
        ),
    ]
