# Generated by Django 5.0.2 on 2024-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="So'rov nomi")),
                ("content", models.TextField(verbose_name="So'rov haqida ma'lumot")),
                (
                    "phone",
                    models.CharField(max_length=200, verbose_name="Telefon raqamingiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaat",
                "verbose_name_plural": "Murojaatlar",
                "db_table": "applications",
            },
        ),
    ]
