# Generated by Django 5.0.2 on 2024-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="created_at",
        ),
    ]
