# Generated by Django 5.0.2 on 2024-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_employees_position_alter_employeeposition_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook manzili"),
        ),
    ]
