# Generated by Django 5.0.2 on 2024-02-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_footer_facebook"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=240, verbose_name="Lavozim [position]"),
                ),
            ],
            options={
                "verbose_name": "Lavozim",
                "verbose_name_plural": "Lavozimlar",
                "db_table": "employee_positions",
            },
        ),
        migrations.AlterField(
            model_name="footer",
            name="facebook",
            field=models.URLField(
                blank=True, null=True, verbose_name="Facebook manzili"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.employeepositions",
                verbose_name="Lavozimingiz",
            ),
        ),
        migrations.DeleteModel(
            name="EmployeePosition",
        ),
    ]
