# Generated by Django 5.0.2 on 2024-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_image_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="numbers_of_image",
            field=models.IntegerField(default=0, verbose_name="Rasmlar soni"),
        ),
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
