# Generated by Django 5.0.2 on 2024-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_news_numbers_of_image_news_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_numbers",
            field=models.IntegerField(default=0, verbose_name="Rasmlar soni"),
        ),
    ]
