# Generated by Django 5.0.2 on 2024-02-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_employeepositions_alter_footer_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.employeepositions",
                verbose_name="Lavozimingiz",
            ),
        ),
    ]
