# Generated by Django 5.0.2 on 2024-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_image_image_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name="about",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name="about",
            name="content_uz",
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="To'liq nomi [title]"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="To'liq nomi [title]"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="title_uz",
            field=models.CharField(
                max_length=200, null=True, verbose_name="To'liq nomi [title]"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="address_en",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Manzilingiz"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="address_ru",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Manzilingiz"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="address_uz",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Manzilingiz"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="fullname_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Ism va familiyangiz [fullname]"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="fullname_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Ism va familiyangiz [fullname]"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="fullname_uz",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Ism va familiyangiz [fullname]"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="image_en",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Rasm"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="image_ru",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Rasm"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="image_uz",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Rasm"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Ma'lumot [content]"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Ma'lumot [content]"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_uz",
            field=models.TextField(null=True, verbose_name="Ma'lumot [content]"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Sarlavha [title]"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Sarlavha [title]"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Sarlavha [title]"
            ),
        ),
    ]
