# Generated by Django 5.0.2 on 2024-02-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_employees_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeepositions",
            old_name="position",
            new_name="title",
        ),
    ]
