# Generated by Django 5.0.2 on 2024-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_about_content_en_about_content_ru_about_content_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="about",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="about",
            name="content_uz",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title_uz",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="address_en",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="address_ru",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="address_uz",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="fullname_en",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="fullname_ru",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="fullname_uz",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="image_en",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="image_ru",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="image_uz",
        ),
        migrations.RemoveField(
            model_name="news",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="news",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="news",
            name="content_uz",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_uz",
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["title", "content", "created_at"], name="news_title_43b34d_idx"
            ),
        ),
    ]
