# Generated by Django 5.0.2 on 2024-02-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_position_employeepositions_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeepositions",
            old_name="title",
            new_name="position",
        ),
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.employeepositions",
                verbose_name="Lavozimingiz",
            ),
        ),
    ]
