# Generated by Django 5.0.2 on 2024-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_about_content_en_remove_about_content_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ManyToManyField(to="app.image", verbose_name="Rasm"),
        ),
    ]
