# Generated by Django 5.0.2 on 2024-02-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_news_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_numbers",
            new_name="image_count",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="numbers_of_image",
            new_name="images_count",
        ),
    ]
