# Generated by Django 5.0.2 on 2024-02-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_image_numbers_image_image_count_and_more"),
        ("utils", "0002_state_attr_en_state_attr_ru_state_attr_uz_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "Tizim haqida",
                "verbose_name_plural": "Tizim haqida",
            },
        ),
        migrations.AlterModelOptions(
            name="footer",
            options={
                "verbose_name": "Footer[saytni pasti qismi]",
                "verbose_name_plural": "Footer[saytni pastki qismi]",
            },
        ),
        migrations.RemoveIndex(
            model_name="news",
            name="news_title_43b34d_idx",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image_count",
        ),
        migrations.RemoveField(
            model_name="news",
            name="images_count",
        ),
        migrations.AddField(
            model_name="about",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.state",
                verbose_name="Xolati",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.state",
                verbose_name="Xolati",
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.state",
                verbose_name="Holati",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.state",
                verbose_name="Xolati",
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="phone",
            field=models.CharField(max_length=200, verbose_name="Telefon raqamlar"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["title", "state", "created_at"], name="news_title_3c8f34_idx"
            ),
        ),
    ]
