# Generated by Django 5.0.2 on 2024-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="To'liq nomi [title]"
                    ),
                ),
                (
                    "attr",
                    models.CharField(max_length=200, verbose_name="Qisqa nomi [attr]"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xolat",
                "verbose_name_plural": "Xolatlar",
                "db_table": "state",
            },
        ),
    ]
